name: Mirror to GitLab

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          # Using your specific instance URL
          TARGET_URL: "tools.ages.pucrs.br/2026-2/3jk-5jk/clube-de-leitura-d-elas/app.git"
        run: |
          # 1. Clone the GitHub repo as a bare repository
          git clone --mirror https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git repo.git

          # 2. Push to your specific GitLab instance
          cd repo.git
          git push --mirror https://oauth2:${GITLAB_TOKEN}@${TARGET_URL}
